language: python
python: 3.6

sudo: required
services: docker

before_install:
    - APP_VERSION=$([ -n "${TRAVIS_TAG}" ] && echo "${TRAVIS_TAG#*v}" || echo "${TRAVIS_BRANCH##*/}")
    - DOCKER_IMAGE_VERSION=$([ -n "${TRAVIS_TAG}" ] && echo "${TRAVIS_TAG}" || echo "${TRAVIS_BRANCH##*/}")

install:
  - pip3 install -r requirements/main-pinned.txt
  - pip3 install -r requirements/test-pinned.txt

before_script:
  - sudo service mysql stop     # For some reason conflicts with faf-db
  - git clone https://github.com/FAForever/faf-stack.git faf-stack
      && pushd faf-stack
      && cp -r config.template config
      && popd
  - docker-compose -f faf-stack/docker-compose.yml up -d faf-db
  - export FAF_STACK_DB_IP=$(docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' $(docker ps -q -f "name=faf-db"))
  - while ! docker exec -it faf-db sh -c "mysqladmin ping -h 127.0.0.1 -uroot -pbanana" &> /dev/null ; do
      echo -n ".";
      sleep 1;
    done
  - docker-compose -f faf-stack/docker-compose.yml run faf-db-migrations migrate
  - python3 tests/db_setup.py

script:
  - python3 -m pytest -v --cov replayserver
  - sphinx-build -b text doc _docbuild
  - python3 setup.py bdist

after_success:
  - coveralls
  - export IMAGE_TAG=faf-aio-replayserver;
  - export REPO=faforever/faf-aio-replayserver;
  - sudo rm -rf "./faf-stack"        # faf-db leaves some -r files, docker complains about these
  - if [ -n "${TRAVIS_TAG}" ]; then
    docker build -t ${IMAGE_TAG} --label="version=$(cat VERSION)" . &&
    echo "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_USERNAME}" --password-stdin &&
    docker tag ${IMAGE_TAG} ${REPO}:${DOCKER_IMAGE_VERSION} &&
    docker push ${REPO};
    fi
